In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

df = pd.DataFrame(data)

In [3]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [4]:
 # used to calcuclate a categorical data eg- category store etc given in the data

In [5]:
 # Group by Category and the sum of Sales

In [6]:
df.groupby('Category')['Sales'].sum()
# group by create object

Category
A    570
B    930
Name: Sales, dtype: int64

In [7]:
df.groupby('Store')['Sales'].sum()

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [8]:
# Group by several columns in one statement
df.groupby('Store')[['Sales','Quantity']].sum()

       Sales  Quantity
Store
S1       720        58
S2       780        65

In [9]:
# Group by Categiory and store

In [11]:
df.groupby(['Store','Category'])['Sales'].sum()

Store  Category
S1     A           220
       B           500
S2     A           350
       B           430
Name: Sales, dtype: int64

# Aggregation

In [12]:
# it means incluing several values to find out one output eg - mean , median , std, min, max , count  etc

In [13]:
df['Sales'].mean()

np.float64(187.5)

In [14]:
# aggreagtion also have a fnction
# i.e .agg

In [16]:
df['Sales'].agg(['mean','median','max','min','count','std'])

mean      187.500000
median    190.000000
max       300.000000
min       100.000000
count       8.000000
std        66.062741
Name: Sales, dtype: float64